name: luncher
description: "App for profitable eating in fastfood"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  yandex_mapkit: ^4.0.2
  burger_king_russia_api: ^1.0.0
  kfc_russia_api: ^1.0.0
  vkusnoitochka_api: ^1.0.1
  flutter_bloc: ^8.1.5
  go_router: ^14.1.0
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  
flutter_intl:
  enabled: true
