name: luncher
description: "App for profitable eating in fastfood"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  yandex_mapkit: ^3.4.0
  burger_king_russia_api: ^1.0.0
  kfc_russia_api: ^1.0.0
  vkusnoitochka_api: ^1.0.0
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  
flutter_intl:
  enabled: true
